# Generated by Django 3.0.7 on 2021-01-03 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='switchport',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swichy', to='members.Switch'),
        ),
        migrations.AddField(
            model_name='switch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='switch',
            name='pop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.POP'),
        ),
        migrations.AddField(
            model_name='portconnection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portconnection',
            name='member_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memcon', to='members.Member'),
        ),
        migrations.AddField(
            model_name='portconnection',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Switch'),
        ),
        migrations.AddField(
            model_name='portconnection',
            name='switch_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.SwitchPort'),
        ),
        migrations.AddField(
            model_name='pop',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
