# Generated by Django 3.0.7 on 2020-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201222_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.CharField(choices=[('Full', 'Full'), ('Associate', 'Associate')], default='Full', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
