# Generated by Django 3.0.7 on 2020-12-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201221_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='portconnection',
            name='membership_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PortCapacity',
        ),
    ]
