# Generated by Django 3.0.7 on 2020-12-30 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_auto_20201222_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('serial_no', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=20)),
                ('int_type', models.CharField(default='Ethernet', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Switch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('memname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memname', to='members.Member')),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.SwitchPort')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Switch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
